POST http://localhost:3003/product/create
Content-Type: application/json

    {
        "name": "PRODUTO SEM TAGg",
        "tags": [""]
    }

###

GET http://localhost:3003/product
Content-Type: application/json

    {
        "tags": ["casual", "metal"]
    }